# see https://jekyllrb.com/docs/configuration/default/ for options

title: "StrockDev"
description: "A place to host my projects and share my knowledge"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
