---
- name: update grub and initramfs
  ansible.builtin.shell: |
    update-grub
    update-initramfs -u -k all
  changed_when: true

- name: reboot proxmox
  ansible.builtin.reboot:
    reboot_timeout: 120

- name: restart lxc 200
  ansible.builtin.command: pct reboot 200
  changed_when: true
